import 'package:flutter/material.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall9widget/generated/GeneratedTabBar44Widget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall9widget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall9widget/generated/GeneratedHUB1Widget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall9widget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall9widget/generated/GeneratedGroup7Widget.dart';

/* Frame Android Small - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 641.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 136, 136, 136),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 78.0,
                child: GeneratedTabBar44Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 95.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 95.0,
                child: GeneratedGroup8Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 95.0,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 50.0,
                child: GeneratedHUB1Widget(),
              )
            ]),
      ),
    ));
  }
}
