import 'package:flutter/material.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall8widget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall8widget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall8widget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall8widget/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall8widget/generated/GeneratedBotaoAdicionarDispositivoWidget6.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall8widget/generated/GeneratedTabBar43Widget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall8widget/generated/GeneratedTelaPrincipalWidget.dart';
import 'package:flutterapp/tccapp/generatedandroidsmall8widget/generated/GeneratedGroup13Widget.dart';

/* Frame Android Small - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 641.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 136, 136, 136),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 78.0,
                child: GeneratedTabBar43Widget(),
              ),
              Positioned(
                left: 214.0,
                top: 467.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 67.0,
                child: GeneratedBotaoAdicionarDispositivoWidget6(),
              ),
              Positioned(
                left: 187.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 150.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 150.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 186.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 150.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 150.0,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 332.0,
                top: 266.4156188964844,
                right: null,
                bottom: null,
                width: 21.0,
                height: 36.056251525878906,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 50.0,
                child: GeneratedTelaPrincipalWidget(),
              )
            ]),
      ),
    ));
  }
}
